### ISSUE TITLE
ability to show relative time "in the future"

### ISSUE THREAD

**Issue by NathanWalker** [Helioscene/angular-contextual-date#3]
I don't see that this is possible at the moment with this, but it would be nice if it would give relative time for future dates as well so something like:

Apr. 16th, 2016 (provided the moment this issue was created) would be:
`Apr. 16th, 2016 (7 months from now)`

or Aug. 27th, 2015 would be:
`Aug. 27th (tomorrow)`

**Comment by jgr3go** [comment]
It's not possible right now, correct, though I don't think this would be very hard to implement. I can take a look at this this week and see what I come up with, I agree it would be a nice addition.

**Comment by jgr3go** [comment]
I finally got around to this today and added support for dates in the future, a couple of quick notes:
- The default setting is "7 months from now" as you suggested. I debated this and "in 7 months" as it has more brevity, but I think "from now" is more clear as a default.
- You can always override this by setting the language override for `futurePrefix` and `futureSuffix`. I've added instructions in the README for how to do that. 
- Lastly, 'tomorrow' (and 'yesterday' and friends) would require some more significant thought. For now I've left it as how it works with the dates in the past. Similar to `1 day ago`, it will say `1 day from now`.  Not the most elegant but they both inherit from the same description, so splitting them out into `yesterday` and `tomorrow` requires more work. I'm willing to do it but didn't get around to it as part of this change.

**Comment by NathanWalker** [comment]
Excellent thank you this is exciting!
