### ISSUE TITLE
Ability to set minimum threshold

### ISSUE THREAD

**Issue by abeniwal** [Helioscene/angular-contextual-date#4]
When displaying dates that were a very short time ago (for example, when using this on content that was just created), it shows that something was milliseconds ago. Can we have a new option to set a minimum threshold? For example, I want anything that was less than five seconds ago to say "Just Now"

**Comment by jgr3go** [comment]
This was just merged into 0.3.0 . The service now has a `.config.thresholds.now` setting, where you can set the number of milliseconds that 'now' will display before the relative time takes over.
